"""
Macedonian → English vocabulary and ambiguity heuristics.

Used as the rule-based fallback for Stage 1 (Analyze) and Stage 2
(Decide Context) when no LLM is configured or the model returns nothing.
"""

MK_DICT: dict[str, str] = {
    "павлака": "sour cream",
    "кисела павлака": "sour cream cultured",
    "сирење": "white cheese feta",
    "кромид": "onion raw",
    "лук": "garlic raw",
    "домат": "tomato raw",
    "домати": "tomatoes raw",
    "краставица": "cucumber raw",
    "пиперка": "pepper paprika spice",
    "суви пиперки": "peppers dried",
    "свежа пиперка": "peppers sweet raw",
    "зелена пиперка": "peppers sweet green raw",
    "црвена пиперка": "peppers sweet red raw",
    "лута пиперка": "peppers chili hot raw",
    "црвен пипер": "spices paprika red pepper",
    "масло": "oil olive cooking",
    "зејтин": "oil olive",
    "сончогледово масло": "oil sunflower",
    "путер": "butter salted",
    "маргарин": "margarine",
    "јајце": "egg whole raw",
    "јајца": "egg whole raw",
    "жолчки": "egg yolks",
    "белки": "egg whites",
    "брашно": "wheat flour white",
    "шеќер": "sugar granulated",
    "шеќер во прав": "sugar powdered",
    "ванилин шеќер": "sugar vanilla",
    "сол": "salt table",
    "сол по потреба": "salt table",
    "млеко": "milk whole",
    "кондензирано млеко": "milk condensed",
    "вода": "water",
    "вода по потреба": "water",
    "масло по потреба": "oil olive cooking",
    "грав": "beans navy white dried",
    "бел грав": "beans navy white",
    "леќа": "lentils raw",
    "наут": "chickpeas garbanzo",
    "ориз": "rice white",
    "тестенини": "pasta dry",
    "макарони": "pasta macaroni",
    "шпагети": "pasta spaghetti",
    "месо": "meat beef",
    "пилешко": "chicken breast raw",
    "пилешко месо": "chicken breast",
    "говедско": "beef ground raw",
    "говедско месо": "beef",
    "свинско": "pork fresh raw",
    "свинско месо": "pork",
    "јагнешко": "lamb ground raw",
    "јагнешко месо": "lamb",
    "риба": "fish",
    "шунка": "ham pork cured",
    "сланина": "bacon pork cured",
    "чадена сланина": "bacon pork smoked",
    "маст": "lard pork fat",
    "свинска маст": "lard",
    "суво месо": "pork cured dried",
    "маслинки": "olives ripe canned",
    "оцет": "vinegar red wine",
    "вински оцет": "vinegar red wine",
    "вино": "wine red",
    "бело вино": "wine white",
    "мед": "honey",
    "прашок за печење": "baking powder",
    "сода бикарбона": "baking soda",
    "цимет": "cinnamon spices",
    "оригано": "oregano dried spices",
    "нане": "mint herbs dried",
    "нане по потреба": "mint herbs",
    "магдонос": "parsley fresh",
    "копар": "dill fresh herbs",
    "ловоров лист": "bay leaf spices",
    "бибер": "pepper black spices",
    "ореви": "walnuts english",
    "бадеми": "almonds",
    "лешници": "hazelnuts",
    "сусам": "sesame seeds",
    "тиквини семки": "pumpkin seeds",
    "сончоглед": "sunflower seeds",
    "јаболка": "apples raw",
    "јаболко": "apple raw",
    "лимон": "lemon juice",
    "портокал": "orange raw",
    "малини": "raspberries",
    "јагоди": "strawberries raw",
    "боровинки": "blueberries raw",
    "грозје": "grapes raw",
    "банана": "bananas raw",
    "компир": "potatoes raw",
    "морков": "carrots raw",
    "спанаќ": "spinach raw",
    "зелка": "cabbage raw",
    "праз": "leeks raw",
    "печурки": "mushrooms white raw",
    "буковец": "mushrooms oyster",
    "шампињони": "mushrooms white raw",
    "тиквица": "zucchini squash raw",
    "патлиџан": "eggplant raw",
    "зеленчук": "vegetables mixed",
    "рикота": "ricotta cheese",
    "мозарела": "mozzarella cheese",
    "пармезан": "parmesan cheese",
    "горгонзола": "cheese blue gorgonzola",
    "кашкавал": "cheese yellow cheddar",
    "мешан сув зачин": "spices mixed herbs dried",
    "зачин": "spices herbs mixed",
    "суви зачини": "spices dried mixed",
    "бисквити": "cookies biscuits",
    "чоколадо": "chocolate dark",
    "какао": "cocoa powder",
    "желатин": "gelatin",
    "скроб": "starch cornstarch",
}

# Generic terms that usually map to several USDA categories → need recipe context.
GENERIC_MK = {
    "павлака", "сирење", "месо", "пиперка", "масло", "млеко",
    "маст", "суво месо", "маслинки", "грав", "риба", "леќа",
}
GENERIC_EN = {
    "oil", "cheese", "meat", "cream", "pepper", "milk", "butter",
    "flour", "sugar", "salt", "beans", "nuts", "fish",
}
